name: Deploy via SSH

on:
  push:
    branches: [master] # Vérifie bien si c'est 'main' ou 'master' ici !

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute script on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # On lance le script qu'on vient de mettre à jour
          script: /var/www/mmiart26/deploiement.sh
